name: Build and deploy Python app to Azure Web App - neuraPriceAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
        working-directory: Backend/API

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: Backend/API

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: Backend/API

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            Backend/API/release.zip
            !Backend/API/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
        working-directory: Backend/API

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2C719744AAB24DFD9E437B2FAE37AC05 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D1DFDC171338411FB735607447D3B73E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_14CD96CB88E04D73B155B970C6576ACF }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'neuraPriceAPI'
          slot-name: 'Production'
